server.port=8080
spring.main.banner-mode=off
server.forward-headers-strategy=native

app.keycloak.logout-url=https://auth.nsantiago.me/realms/test-mfa-app/protocol/openid-connect/logout
app.base-url=https://test-mfa.nsantiago.me

# Keycloak OIDC configuration
spring.security.oauth2.client.registration.keycloak.client-id=test-mfa-app
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=https://auth.nsantiago.me/realms/test-mfa-app

# BambooHR OAuth2 Config
bamboohr.client-id=developer_portal-5e5682c4e314161050e7842330448e890613a0c8
bamboohr.client-secret=8fdcbfa176f24a90b238bbbc019966cd7de992561406d4cfe3047eb55331a57a9bbabd123817b46c
bamboohr.redirect-uri=https://test-mfa.nsantiago.me/bamboohr/callback
bamboohr.company-domain=nickysantiago
