server.port=8080
spring.main.banner-mode=off
server.forward-headers-strategy=native
app.base-url=https://test-mfa.nsantiago.me


# Auth0 logout handler properties
app.auth0.logout-url=https://auth.nsantiago.me/v2/logout
app.auth0.client-id=${AUTH0_CLIENT_ID}
app.base-url=https://test-mfa.nsantiago.me

# Auth0 OIDC configuration
spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/auth0

# Auth0 provider — trailing slash is required, must match issuer in discovery doc
spring.security.oauth2.client.provider.auth0.issuer-uri=https://auth.nsantiago.me/

# Keycloak OIDC configuration
#spring.security.oauth2.client.registration.keycloak.client-id=test-mfa-app
#spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
#app.keycloak.logout-url=https://auth.nsantiago.me/realms/test-mfa-app/protocol/openid-connect/logout
#spring.security.oauth2.client.provider.keycloak.issuer-uri=https://auth.nsantiago.me/realms/test-mfa-app
